
#root -b -q 'src/ProcessPtCh.C("60GeVJets", "60GeVJets_JetES5Perc")'
#root -b -q 'src/ProcessPtCh.C("30GeVJets", "30GeVJets_JetES5Perc")'
#root -b -q 'src/ProcessPtCh.C("15GeVJets", "15GeVJets_JetES5Perc")'
#root -b -q 'src/ProcessFineFCalPtCh.C("60GeVJets", "60GeVJets")'
#root -b -q 'src/ProcessFineFCalPtCh.C("30GeVJets", "30GeVJets")'
#root -b -q 'src/CombineFineFCalPtCh.C("60GeVJets")'
#root -b -q 'src/CombineFineFCalPtCh.C("30GeVJets")'
#root -b -q 'src/ProcessDPhi.C("60GeVJets", "60GeVJets_JetES5Perc")'
#root -b -q 'src/ProcessDPhi.C("30GeVJets", "30GeVJets_JetES5Perc")'
#root -b -q 'src/ProcessDPhi.C("15GeVJets", "15GeVJets_JetES5Perc")'
#root -b -q 'src/ProcessJets.C("60GeVJets", "60GeVJets_JetES5Perc", 4)'
#root -b -q 'src/ProcessJets.C("30GeVJets", "30GeVJets_JetES5Perc", 4)'
  
#root -b -q 'src/PlotFineFCalPtCh.C("60GeVJets", "60GeVJets", "60GeVJets_JetES5Perc")'
#root -b -q 'src/PlotFineFCalPtCh.C("30GeVJets", "30GeVJets", "30GeVJets_JetES5Perc")'
#root -b -q 'src/PlotDPhi.C("60GeVJets", "60GeVJets_JetES5Perc")'
#root -b -q 'src/PlotDPhi.C("30GeVJets", "30GeVJets_JetES5Perc")'
#root -b -q 'src/PlotDPhi.C("15GeVJets", "15GeVJets_JetES5Perc")'
#root -b -q 'src/PlotJets.C("60GeVJets_JetES5Perc")'
#root -b -q 'src/PlotJets.C("30GeVJets_JetES5Perc")'

root -b -q 'src/CalculateIAAShifts.C("60GeVJets", "60GeVJets_JetES5Perc")'
root -b -q 'src/CalculateIAAShifts.C("30GeVJets", "30GeVJets_JetES5Perc")'
root -b -q 'src/CalculateIAAShifts.C("15GeVJets", "15GeVJets_JetES5Perc")'

root -b -q 'src/PlotPtCh.C("60GeVJets", "60GeVJets_JetES5Perc")'
root -b -q 'src/PlotPtCh.C("30GeVJets", "30GeVJets_JetES5Perc")'
root -b -q 'src/PlotPtCh.C("15GeVJets", "15GeVJets_JetES5Perc")'
