Universe = vanilla
Notification = Complete
Executable = /atlasgpfs01/usatlas/workarea/jeff/HadronYieldsAnalysis/bin/run.exe
Priority = +1
GetEnv = True
InitialDir = /atlasgpfs01/usatlas/workarea/jeff/HadronYieldsAnalysis/run
accounting_group = group_atlas.boulder

#Arguments = JetHadronSkimmer data_020 $(runNumber) pPb16_5TeV Collisions Jet false false false
Arguments = JetHadronSkimmer data_020 $(runNumber) pPb16_5TeV Collisions MinBias false false false
#Arguments = ZDCAnalysis data_020 $(runNumber) pPb16_5TeV Collisions MinBias false false false
Error = /atlasgpfs01/usatlas/workarea/jeff/HadronYieldsAnalysis/run/errors/$(runNumber).err
Log = /atlasgpfs01/usatlas/workarea/jeff/HadronYieldsAnalysis/run/logs/$(runNumber).log
Output = /atlasgpfs01/usatlas/workarea/jeff/HadronYieldsAnalysis/run/outputs/$(runNumber).out
Queue runNumber in (312796 312837 312937 312945 312968 314199)
#Queue runNumber in (312649 312796 312837 312937 312945 312968 314199)

#Arguments = JetHadronSkimmer data_000 $(runNumber) pp17_5TeV Collisions MinBias false false false
#Error = /atlasgpfs01/usatlas/workarea/jeff/HadronYieldsAnalysis/run/errors/$(runNumber).err
#Log = /atlasgpfs01/usatlas/workarea/jeff/HadronYieldsAnalysis/run/logs/$(runNumber).log
#Output = /atlasgpfs01/usatlas/workarea/jeff/HadronYieldsAnalysis/run/outputs/$(runNumber).out
#Queue runNumber in (340644 340683 340697 340718 340814 340849 340850 340910 340925 340973 341027 341123 341184)
